name = "pphi2"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Pphi2"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "GaussianField"
scope = "mrdouglasny"
git = "https://github.com/mrdouglasny/gaussian-field.git"
rev = "cylinder"

[[require]]
name = "bochner"
scope = "mrdouglasny"
git = "https://github.com/mrdouglasny/bochner.git"
rev = "main"

[[lean_lib]]
name = "Pphi2"
needs = ["Common"]

[[lean_lib]]
name = "Common"
